import type {
  BuildAction,
  BuildGraph,
  Candidate,
  ContentCatalogEntry,
  DeepLimits,
  ConditionEvidence,
  MetricSet,
  ObjectiveSpec,
  RankedScenarioId,
  ScenarioSpec,
  SearchStopReason,
} from "../schemas.js";
export type { SearchStopReason } from "../schemas.js";

export const SEARCH_DOMAINS = [
  "rules",
  "identity",
  "skills",
  "gear",
  "tree",
  "actor",
  "config",
  "external",
  "progression",
] as const;

export type SearchDomain = (typeof SEARCH_DOMAINS)[number];
export type MetricVector = Readonly<MetricSet>;
export type MetricDirection = "maximize" | "minimize";
export type MetricRole = "offence" | "defence" | "utility";

export interface MetricSpec {
  readonly key: string;
  readonly direction: MetricDirection;
  readonly weight?: number;
  readonly role?: MetricRole;
}

export type ConstraintOperator = "gte" | "gt" | "lte" | "lt" | "eq" | "ne";

export interface HardConstraint {
  readonly id: string;
  readonly metric: string;
  readonly operator: ConstraintOperator;
  readonly value: number;
  /** Empty/omitted means every sustainable scenario. */
  readonly scenarios?: readonly string[];
}

export interface SearchObjective {
  readonly primaryMetric: string;
  readonly primaryScenario: string;
  readonly metrics: readonly MetricSpec[];
  readonly scenarioWeights: Readonly<Record<string, number>>;
  readonly hardConstraints: readonly HardConstraint[];
  readonly candidatePolicy?: {
    readonly budgetDivine?: number;
    readonly sources: {
      readonly currentBuild: boolean;
      readonly uniques: boolean;
      readonly targetRares: boolean;
      readonly trade: boolean;
    };
    readonly locks?: {
      readonly class: boolean;
      readonly ascendancy: boolean;
      readonly mainSkill: boolean;
      readonly fields: readonly string[];
    };
  };
}

export interface SearchCandidate<Action = unknown> {
  readonly id: string;
  readonly baseFingerprint: string;
  readonly actions: readonly Action[];
  readonly metricsByScenario?: Readonly<Record<string, MetricVector>>;
  readonly domain?: SearchDomain;
  readonly parentIds?: readonly string[];
  readonly estimatedCost?: number;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

export interface EvaluatedCandidate<Action = unknown> extends SearchCandidate<Action> {
  readonly metricsByScenario: Readonly<Record<string, MetricVector>>;
}

export interface DomainSearchState<Action = unknown> {
  /** Deterministic adapters consume proposals generated by the PoB/catalog seam. */
  readonly domainCandidates?: Partial<Readonly<Record<SearchDomain, readonly SearchCandidate<Action>[]>>>;
  readonly buildXml?: string;
  readonly scenarioSpecs?: readonly ScenarioSpec[];
  readonly evidence?: readonly ConditionEvidence[];
  readonly contentCatalog?: readonly ContentCatalogEntry[];
  readonly domainGraph?: BuildGraph;
  readonly mechanicAdapterIds?: readonly string[];
  readonly proposalInputs?: FullDomainProposalInputs;
  readonly [key: string]: unknown;
}

export interface FullDomainProposalInputs {
  readonly gear?: readonly {
    readonly id: string;
    readonly slot: string;
    readonly itemId: number;
    readonly itemSetId?: number;
    readonly description?: string;
    readonly costDivine?: number;
  }[];
  readonly links?: readonly {
    readonly id: string;
    readonly group: number;
    readonly gems: readonly (string | Readonly<Record<string, unknown>>)[];
    readonly description?: string;
  }[];
  readonly config?: readonly {
    readonly id: string;
    readonly name: string;
    readonly value: unknown;
    readonly description?: string;
  }[];
  readonly tree?: readonly {
    readonly id: string;
    readonly nodeIds: readonly number[];
    readonly mastery?: { readonly nodeId: number; readonly effectId: number };
    readonly description?: string;
  }[];
}

export interface SearchProgress<Action = unknown> {
  readonly phase: "searching" | "converged" | "stopped";
  readonly round: number;
  readonly domain?: SearchDomain;
  readonly evaluations: number;
  readonly frontier: readonly EvaluatedCandidate<Action>[];
  readonly elapsedMs: number;
}

export interface SearchResult<Action = unknown> {
  readonly frontier: readonly EvaluatedCandidate<Action>[];
  readonly beam: readonly EvaluatedCandidate<Action>[];
  readonly rounds: number;
  readonly evaluations: number;
  readonly modelCalls: number;
  readonly elapsedMs: number;
  readonly stopReason: SearchStopReason;
  readonly selections: CandidateSelections<Action>;
}

export interface CandidateSelections<Action = unknown> {
  readonly offence?: EvaluatedCandidate<Action>;
  readonly balanced?: EvaluatedCandidate<Action>;
  readonly defence?: EvaluatedCandidate<Action>;
}

export type PublicBuildAction = BuildAction;
export type PublicCandidate = Candidate;
export type PublicObjectiveSpec = ObjectiveSpec;
export type PublicDeepLimits = DeepLimits;
export type SustainableScenario = RankedScenarioId;
